name: SauceDemo Automation CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean compile

      - name: Run tests
        run: mvn test -Dbrowser=${{ matrix.browser }}

      - name: Archive ExtentReports
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: target/extent-report.html

      - name: Archive Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: target/screenshots/
